- name: Create credential type
  hosts: localhost
  connection: local
  tasks:
    - name: "Add EE Builder credential type"
      ansible.controller.credential_type:
        name: "EE Builder"
        description: "Credentials utilized by infra.ee_utilities.ee_builder"
        kind: cloud
        inputs:
          fields:
            - id: base_registry_username
              type: string
              label: EE Base Registry Username
            - id: base_registry_password
              type: string
              label: EE Base Registry Password
              secret: true
            - id: registry_dest
              type: string
              label: Destination registry
            - id: registry_username
              type: string
              label: Destination registry Username
            - id: registry_password
              type: string
              label: Destination registry Password
              secret: true
            - id: ah_host
              type: string
              label: EE Automation Hub
            - id: ah_token
              type: string
              label: EE Automation Hub Token
              secret: true
          required:
            - ee_base_registry_username
            - ee_base_registry_password
            - ee_registry_dest
            - ee_registry_username
            - ee_registry_password
            - ee_ah_host
            - ee_ah_token
        injectors:
          extra_vars:
            ee_base_registry_username: "{{ '{{' }} base_registry_username {{ '}}' }}"
            ee_base_registry_password: "{{ '{{' }} base_registry_password {{ '}}' }}"
            ee_registry_dest: "{{ '{{' }} registry_dest {{ '}}' }}"
            ee_registry_username: "{{ '{{' }} registry_username {{ '}}' }}"
            ee_registry_password: "{{ '{{' }} registry_password {{ '}}' }}"
            ee_ah_host: "{{ '{{' }} ah_host {{ '}}' }}"
            ee_ah_token: "{{ '{{' }} ah_token {{ '}}' }}"
