- name: Create credential type
  hosts: localhost
  connection: local
  tasks:
    - name: "Add EE Builder credential type"
      ansible.controller.credential_type:
        name: "EE Builder"
        description: "Credentials utilized by infra.ee_utilities.ee_builder"
        kind: cloud
        inputs:
          fields:
            - id: base_registry_username
              type: string
              label: EE Base Registry Username
            - id: base_registry_password
              type: string
              label: EE Base Registry Password
              secret: true
            - id: registry_dest
              type: string
              label: Destination registry
            - id: registry_username
              type: string
              label: Destination registry Username
            - id: registry_password
              type: string
              label: Destination registry Password
              secret: true
            - id: ah_host
              type: string
              label: EE Automation Hub
            - id: ah_token
              type: string
              label: EE Automation Hub Token
              secret: true
          required:
            - ee_base_registry_username
            - ee_base_registry_password
            - ee_registry_dest
            - ee_registry_username
            - ee_registry_password
            - ee_ah_host
            - ee_ah_token
        injectors:
          extra_vars:
            ee_base_registry_username: "{{ '{{' }} base_registry_username {{ '}}' }}"
            ee_base_registry_password: "{{ '{{' }} base_registry_password {{ '}}' }}"
            ee_registry_dest: "{{ '{{' }} registry_dest {{ '}}' }}"
            ee_registry_username: "{{ '{{' }} registry_username {{ '}}' }}"
            ee_registry_password: "{{ '{{' }} registry_password {{ '}}' }}"
            ee_ah_host: "{{ '{{' }} ah_host {{ '}}' }}"
            ee_ah_token: "{{ '{{' }} ah_token {{ '}}' }}"

    - name: Create Credential
      ansible.controller.credential:
        name: "EE Builder"
        organization: "Default"
        credential_type: "EE Builder"
        state: present
        update_secrets: false
        inputs:
          base_registry_username: "mkletz"
          base_registry_password: "change_me"
          registry_dest: "change_me"
          registry_username: "Admin"
          registry_password: "change_me"
          ah_host: "change_me"
          ah_token: "change_me"

    - name: "Add job template"
      ansible.controller.job_template:
        name: 'AAP // Create Execution Environments'
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "ee-creation"
        playbook: "build-ee.yml"
        state: "present"
        become_enabled: true
        credentials:
          - "EE Builder"
          - "RHEL admin"
        labels:
          - "AAP"
